#!/bin/sh
# ------------------------------
# PaperMC auto-updater
#
# /runner/entrypoint
# ------------------------------

echo "> Welcome! using product: $PRODUCT"

echo "> Checking if the OVERRIDE_VERSION env variable was set..."

if [ -z ${OVERRIDE_VERSION+x} ];
then
	# Variable is not set.
	echo "> Variable not set, querying for latest supported minecraft version..."
	LATEST_MC=$(wget -q -O- https://papermc.io/api/v1/$PRODUCT | jq ".versions[0]" | sed 's/"//g')
	echo "> Found version $LATEST_MC! Downloading latest build..."
else
	# Variable is set.
	echo "> Override Variable set! Using overridden version $OVERRIDE_VERSION"
	LATEST_MC=$OVERRIDE_VERSION
fi



wget -q -O /runner/app.jar https://papermc.io/api/v1/$PRODUCT/$LATEST_MC/latest/download

if [ $? -eq 0 ]; then
	echo "> Successfully downloaded! Starting..."
	echo ""
	# possible to override arguments
	/runner/runner $@
else
	echo "> Failed to download $PRODUCT. Exiting..."
	exit 1
fi