#!/bin/sh
# ------------------------------
# PaperMC Optimized Runner
#
# /runner/runner
# ------------------------------
# Flag Breakdown
#
# 1. (Paper): Ignore java version on startup (allow booting with brand-new java versions)
# 2. Auto-agree to the Minecraft EULA
# 3. Various --add-opens for various classes
#    > java.lang - (eg. LuckPerms, BKCommonLib)
#    > java.lang.reflect - LuckPerms, StickyAPI FieldUtil, Warrior, etc.
#    > java.net - Plan dependency downloader
# 4. Aikar's minecraft flags
# ------------------------------

echo "runner > In directory: '$(pwd)'"

echo "runner > Found JAR Path: '$JAR_PATH'"
echo "runner > Found JVM Options: '$JVM_OPTS'"
echo "runner > Found Application Options: '$APP_OPTS'"

java -DPaper.IgnoreJavaVersion=true -Dcom.mojang.eula.agree=true --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true $JVM_OPTS -jar $JAR_PATH nogui $APP_OPTS
