#!/bin/sh
# ------------------------------
# Paper auto-updater
#
# /runner/entrypoint
# ------------------------------

echo "> Querying for latest supported minecraft version..."

LATEST_MC=$(wget -q -O- https://papermc.io/api/v1/paper | jq ".versions[0]" | sed 's/"//g')

echo "> Found version $LATEST_MC! Downloading latest build..."


wget -q -O /runner/paper.jar https://papermc.io/api/v1/paper/$LATEST_MC/latest/download

if [ $? -eq 0 ]; then
	echo "> Successfully downloaded! Starting..."
	echo ""
	# possible to override arguments
	/runner/runner $@
else
	echo "> Failed to download paper. Exiting..."
	exit 1
fi