#!/bin/sh
# ------------------------------
# GeyserMC auto-updater
#
# /runner/entrypoint
# ------------------------------


# default auto-updating JAR path.
JAR_PATH="/runner/app.jar"

# default repository branch to download from
BRANCH="master"

JVM_OPTS="$@ $JVM_OPTS "

echo "entrypoint > Found JVM Options: '$JVM_OPTS'"
echo "entrypoint > Found Application Options: '$APP_OPTS'"

echo "entrypoint > Welcome!"

echo "entrypoint > Checking if OVERRIDE_JAR_PATH env variable was set..."

if [ ! -z "$OVERRIDE_JAR_PATH" ];
then
	# Variable was set, skip the download and pass the variable to the runner.
	echo "entrypoint > OVERRIDE_JAR_PATH found! ('${OVERRIDE_JAR_PATH}') Starting..."
	JAR_PATH=$OVERRIDE_JAR_PATH
	# source runner to pass through env vars
	. /runner/runner
else

	# Check if an override branch was set
	
	echo "entrypoint > Checking if OVERRIDE_BRANCH env variable was set..."
	
	if [ ! -z "$OVERRIDE_BRANCH" ];
	then
		# Variable was set
		echo "entrypoint > OVERRIDE_BRANCH found! ('${OVERRIDE_BRANCH}')"
		BRANCH=$OVERRIDE_BRANCH
	fi
	
	echo "entrypoint > Checking if the OVERRIDE_JAR_DL_PATH env variable was set..."

	if [ -z ${OVERRIDE_JAR_DL_PATH} ];
	then
		# Variable is not set
		echo "entrypoint > Variable not set, using default ($JAR_PATH)..."
	else
		# Variable is set.
		echo "entrypoint > Override Variable set! Using overriden JAR download path '$OVERRIDE_JAR_DL_PATH'"
		JAR_PATH=$OVERRIDE_JAR_DL_PATH	
	fi

	echo "entrypoint > Downloading latest build... (branch: '$BRANCH')"
	
	# echo "debug > '$(echo "${BRANCH}" | sed -f /runner/url_escape.sed)'"

	wget -q -O $JAR_PATH https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/$(echo "${BRANCH}" | sed -f /runner/url_escape.sed)/lastSuccessfulBuild/artifact/bootstrap/standalone/target/Geyser.jar

	if [ $? -eq 0 ]; then
		echo "entrypoint > Successfully downloaded! Starting..."
		echo ""
		# source runner to pass through env vars
		. /runner/runner
	else
		echo "entrypoint > Failed to download Geyser. Exiting..."
		exit 1
	fi
fi
