#!/bin/sh
# ------------------------------
# GeyserMC auto-updater
#
# /runner/entrypoint
# ------------------------------

# default auto-updating JAR path.
JAR_PATH="/runner/app.jar"

JVM_OPTS="$@ $JVM_OPTS "

echo "entrypoint > In directory: '$(pwd)'"

echo "entrypoint > Found JVM Options: '$JVM_OPTS'"
echo "entrypoint > Found Application Options: '$APP_OPTS'"

echo "entrypoint > Welcome!"

echo "entrypoint > Checking if OVERRIDE_JAR_PATH env variable was set..."

if [ ! -z ${OVERRIDE_JAR_PATH} ];
then
	# Variable was set, skip the download and pass the variable to the runner.
	echo "entrypoint > OVERRIDE_JAR_PATH found! ('${OVERRIDE_JAR_PATH}') Starting... (in directory '$(pwd)')"
	JAR_PATH=$OVERRIDE_JAR_PATH
	# source runner to pass through env vars
	. /runner/runner
else
	echo "entrypoint > Checking if the OVERRIDE_BRANCH env variable was set..."

	if [ -z ${OVERRIDE_BRANCH} ];
	then
		# Variable is not set.
		echo "entrypoint > Variable not set, querying for default branch..."
		DEFAULT_BRANCH=$(dltool latestmc geyser)
		echo "entrypoint > Found branch $DEFAULT_BRANCH! Downloading latest build..."
	else
		# Variable is set.
		echo "entrypoint > Override Variable set! Using overridden branch $OVERRIDE_BRANCH"
		DEFAULT_BRANCH=$OVERRIDE_BRANCH
	fi
	
	echo "entrypoint > Checking if the OVERRIDE_JAR_DL_PATH env variable was set..."
	
	if [ -z ${OVERRIDE_JAR_DL_PATH} ];
	then
		# Variable is not set
		echo "entrypoint > Variable not set, using default ($JAR_PATH)..."
	else
		# Variable is set.
		echo "entrypoint > Override Variable set! Using overriden JAR download path '$OVERRIDE_JAR_DL_PATH'"
		JAR_PATH=$OVERRIDE_JAR_DL_PATH	
	fi
	
	wget -q -O $JAR_PATH $(dltool download geyser $DEFAULT_BRANCH)

	if [ $? -eq 0 ]; then
		echo "entrypoint > Successfully downloaded! Starting... (in directory '$(pwd)')"
		echo ""
		# source runner to pass through env vars
		. /runner/runner
	else
		echo "entrypoint > Failed to download Geyser. Exiting..."
		exit 1
	fi
fi
